// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: ActivityRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_activity_repository.go -package=mocks . ActivityRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockActivityRepository) GetByID(ctx context.Context, id int64) (*domain.ActivityEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.ActivityEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActivityRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivityRepository)(nil).GetByID), ctx, id)
}

// GetLast mocks base method.
func (m *MockActivityRepository) GetLast(ctx context.Context, userID int64, limit int) ([]domain.ActivityEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ActivityEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockActivityRepositoryMockRecorder) GetLast(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockActivityRepository)(nil).GetLast), ctx, userID, limit)
}

// Save mocks base method.
func (m *MockActivityRepository) Save(ctx context.Context, entry *domain.ActivityEntry) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entry)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockActivityRepositoryMockRecorder) Save(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockActivityRepository)(nil).Save), ctx, entry)
}
