// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: GlucoseRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_glucose_repository.go -package=mocks . GlucoseRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGlucoseRepository is a mock of GlucoseRepository interface.
type MockGlucoseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGlucoseRepositoryMockRecorder
	isgomock struct{}
}

// MockGlucoseRepositoryMockRecorder is the mock recorder for MockGlucoseRepository.
type MockGlucoseRepositoryMockRecorder struct {
	mock *MockGlucoseRepository
}

// NewMockGlucoseRepository creates a new mock instance.
func NewMockGlucoseRepository(ctrl *gomock.Controller) *MockGlucoseRepository {
	mock := &MockGlucoseRepository{ctrl: ctrl}
	mock.recorder = &MockGlucoseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlucoseRepository) EXPECT() *MockGlucoseRepositoryMockRecorder {
	return m.recorder
}

// GetByTimeRange mocks base method.
func (m *MockGlucoseRepository) GetByTimeRange(ctx context.Context, userID int64, from, to time.Time) ([]domain.GlucoseReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTimeRange", ctx, userID, from, to)
	ret0, _ := ret[0].([]domain.GlucoseReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTimeRange indicates an expected call of GetByTimeRange.
func (mr *MockGlucoseRepositoryMockRecorder) GetByTimeRange(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTimeRange", reflect.TypeOf((*MockGlucoseRepository)(nil).GetByTimeRange), ctx, userID, from, to)
}

// GetLast mocks base method.
func (m *MockGlucoseRepository) GetLast(ctx context.Context, userID int64, limit int) ([]domain.GlucoseReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.GlucoseReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockGlucoseRepositoryMockRecorder) GetLast(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockGlucoseRepository)(nil).GetLast), ctx, userID, limit)
}

// Save mocks base method.
func (m *MockGlucoseRepository) Save(ctx context.Context, reading *domain.GlucoseReading) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, reading)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGlucoseRepositoryMockRecorder) Save(ctx, reading any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGlucoseRepository)(nil).Save), ctx, reading)
}
