// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: CGMClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cgm_client.go -package=mocks . CGMClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCGMClient is a mock of CGMClient interface.
type MockCGMClient struct {
	ctrl     *gomock.Controller
	recorder *MockCGMClientMockRecorder
	isgomock struct{}
}

// MockCGMClientMockRecorder is the mock recorder for MockCGMClient.
type MockCGMClientMockRecorder struct {
	mock *MockCGMClient
}

// NewMockCGMClient creates a new mock instance.
func NewMockCGMClient(ctrl *gomock.Controller) *MockCGMClient {
	mock := &MockCGMClient{ctrl: ctrl}
	mock.recorder = &MockCGMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCGMClient) EXPECT() *MockCGMClientMockRecorder {
	return m.recorder
}

// GetEntries mocks base method.
func (m *MockCGMClient) GetEntries(ctx context.Context, since time.Time, count int) ([]domain.GlucoseReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntries", ctx, since, count)
	ret0, _ := ret[0].([]domain.GlucoseReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntries indicates an expected call of GetEntries.
func (mr *MockCGMClientMockRecorder) GetEntries(ctx, since, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntries", reflect.TypeOf((*MockCGMClient)(nil).GetEntries), ctx, since, count)
}

// VerifyConnection mocks base method.
func (m *MockCGMClient) VerifyConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyConnection indicates an expected call of VerifyConnection.
func (mr *MockCGMClientMockRecorder) VerifyConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyConnection", reflect.TypeOf((*MockCGMClient)(nil).VerifyConnection), ctx)
}
