// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: ExternalAccountRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_external_account_repository.go -package=mocks . ExternalAccountRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalAccountRepository is a mock of ExternalAccountRepository interface.
type MockExternalAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockExternalAccountRepositoryMockRecorder is the mock recorder for MockExternalAccountRepository.
type MockExternalAccountRepositoryMockRecorder struct {
	mock *MockExternalAccountRepository
}

// NewMockExternalAccountRepository creates a new mock instance.
func NewMockExternalAccountRepository(ctrl *gomock.Controller) *MockExternalAccountRepository {
	mock := &MockExternalAccountRepository{ctrl: ctrl}
	mock.recorder = &MockExternalAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAccountRepository) EXPECT() *MockExternalAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalAccountRepository) Create(ctx context.Context, account *domain.ExternalAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExternalAccountRepositoryMockRecorder) Create(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalAccountRepository)(nil).Create), ctx, account)
}

// GetByProvider mocks base method.
func (m *MockExternalAccountRepository) GetByProvider(ctx context.Context, provider domain.Provider, externalID string) (*domain.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProvider", ctx, provider, externalID)
	ret0, _ := ret[0].(*domain.ExternalAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProvider indicates an expected call of GetByProvider.
func (mr *MockExternalAccountRepositoryMockRecorder) GetByProvider(ctx, provider, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProvider", reflect.TypeOf((*MockExternalAccountRepository)(nil).GetByProvider), ctx, provider, externalID)
}
