// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: CGMConnectionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cgm_repository.go -package=mocks . CGMConnectionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCGMConnectionRepository is a mock of CGMConnectionRepository interface.
type MockCGMConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCGMConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockCGMConnectionRepositoryMockRecorder is the mock recorder for MockCGMConnectionRepository.
type MockCGMConnectionRepositoryMockRecorder struct {
	mock *MockCGMConnectionRepository
}

// NewMockCGMConnectionRepository creates a new mock instance.
func NewMockCGMConnectionRepository(ctrl *gomock.Controller) *MockCGMConnectionRepository {
	mock := &MockCGMConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockCGMConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCGMConnectionRepository) EXPECT() *MockCGMConnectionRepositoryMockRecorder {
	return m.recorder
}

// Deactivate mocks base method.
func (m *MockCGMConnectionRepository) Deactivate(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockCGMConnectionRepositoryMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockCGMConnectionRepository)(nil).Deactivate), ctx, id)
}

// Delete mocks base method.
func (m *MockCGMConnectionRepository) Delete(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCGMConnectionRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCGMConnectionRepository)(nil).Delete), ctx, userID)
}

// GetAllActive mocks base method.
func (m *MockCGMConnectionRepository) GetAllActive(ctx context.Context) ([]domain.CGMConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActive", ctx)
	ret0, _ := ret[0].([]domain.CGMConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActive indicates an expected call of GetAllActive.
func (mr *MockCGMConnectionRepositoryMockRecorder) GetAllActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActive", reflect.TypeOf((*MockCGMConnectionRepository)(nil).GetAllActive), ctx)
}

// GetByUserID mocks base method.
func (m *MockCGMConnectionRepository) GetByUserID(ctx context.Context, userID int64) (*domain.CGMConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.CGMConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCGMConnectionRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCGMConnectionRepository)(nil).GetByUserID), ctx, userID)
}

// UpdateLastSyncedAt mocks base method.
func (m *MockCGMConnectionRepository) UpdateLastSyncedAt(ctx context.Context, id int64, syncedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSyncedAt", ctx, id, syncedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSyncedAt indicates an expected call of UpdateLastSyncedAt.
func (mr *MockCGMConnectionRepositoryMockRecorder) UpdateLastSyncedAt(ctx, id, syncedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSyncedAt", reflect.TypeOf((*MockCGMConnectionRepository)(nil).UpdateLastSyncedAt), ctx, id, syncedAt)
}

// Upsert mocks base method.
func (m *MockCGMConnectionRepository) Upsert(ctx context.Context, conn *domain.CGMConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCGMConnectionRepositoryMockRecorder) Upsert(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCGMConnectionRepository)(nil).Upsert), ctx, conn)
}
