// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: ReminderRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_reminder_repository.go -package=mocks . ReminderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReminderRepository is a mock of ReminderRepository interface.
type MockReminderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReminderRepositoryMockRecorder
	isgomock struct{}
}

// MockReminderRepositoryMockRecorder is the mock recorder for MockReminderRepository.
type MockReminderRepositoryMockRecorder struct {
	mock *MockReminderRepository
}

// NewMockReminderRepository creates a new mock instance.
func NewMockReminderRepository(ctrl *gomock.Controller) *MockReminderRepository {
	mock := &MockReminderRepository{ctrl: ctrl}
	mock.recorder = &MockReminderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderRepository) EXPECT() *MockReminderRepositoryMockRecorder {
	return m.recorder
}

// GetPending mocks base method.
func (m *MockReminderRepository) GetPending(ctx context.Context, now time.Time) ([]domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", ctx, now)
	ret0, _ := ret[0].([]domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockReminderRepositoryMockRecorder) GetPending(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockReminderRepository)(nil).GetPending), ctx, now)
}

// MarkFired mocks base method.
func (m *MockReminderRepository) MarkFired(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFired", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFired indicates an expected call of MarkFired.
func (mr *MockReminderRepositoryMockRecorder) MarkFired(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFired", reflect.TypeOf((*MockReminderRepository)(nil).MarkFired), ctx, id)
}

// Save mocks base method.
func (m *MockReminderRepository) Save(ctx context.Context, reminder *domain.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockReminderRepositoryMockRecorder) Save(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReminderRepository)(nil).Save), ctx, reminder)
}
