// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user_repository.go -package=mocks . UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// UpdateBolusDrug mocks base method.
func (m *MockUserRepository) UpdateBolusDrug(ctx context.Context, userID int64, drug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBolusDrug", ctx, userID, drug)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBolusDrug indicates an expected call of UpdateBolusDrug.
func (mr *MockUserRepositoryMockRecorder) UpdateBolusDrug(ctx, userID, drug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBolusDrug", reflect.TypeOf((*MockUserRepository)(nil).UpdateBolusDrug), ctx, userID, drug)
}

// UpdateCarbsPerUnit mocks base method.
func (m *MockUserRepository) UpdateCarbsPerUnit(ctx context.Context, id int64, grams float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarbsPerUnit", ctx, id, grams)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCarbsPerUnit indicates an expected call of UpdateCarbsPerUnit.
func (mr *MockUserRepositoryMockRecorder) UpdateCarbsPerUnit(ctx, id, grams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarbsPerUnit", reflect.TypeOf((*MockUserRepository)(nil).UpdateCarbsPerUnit), ctx, id, grams)
}

// UpdateSettings mocks base method.
func (m *MockUserRepository) UpdateSettings(ctx context.Context, userID int64, targetMin, targetMax float64, basalDrug, basalTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, userID, targetMin, targetMax, basalDrug, basalTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserRepositoryMockRecorder) UpdateSettings(ctx, userID, targetMin, targetMax, basalDrug, basalTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserRepository)(nil).UpdateSettings), ctx, userID, targetMin, targetMax, basalDrug, basalTime)
}

// UpdateTimezone mocks base method.
func (m *MockUserRepository) UpdateTimezone(ctx context.Context, userID int64, timezone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimezone", ctx, userID, timezone)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimezone indicates an expected call of UpdateTimezone.
func (mr *MockUserRepositoryMockRecorder) UpdateTimezone(ctx, userID, timezone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimezone", reflect.TypeOf((*MockUserRepository)(nil).UpdateTimezone), ctx, userID, timezone)
}

// UpdateUnits mocks base method.
func (m *MockUserRepository) UpdateUnits(ctx context.Context, id int64, units domain.Units) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUnits", ctx, id, units)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUnits indicates an expected call of UpdateUnits.
func (mr *MockUserRepositoryMockRecorder) UpdateUnits(ctx, id, units any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUnits", reflect.TypeOf((*MockUserRepository)(nil).UpdateUnits), ctx, id, units)
}
