// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: InsulinRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_insulin_repository.go -package=mocks . InsulinRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInsulinRepository is a mock of InsulinRepository interface.
type MockInsulinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInsulinRepositoryMockRecorder
	isgomock struct{}
}

// MockInsulinRepositoryMockRecorder is the mock recorder for MockInsulinRepository.
type MockInsulinRepositoryMockRecorder struct {
	mock *MockInsulinRepository
}

// NewMockInsulinRepository creates a new mock instance.
func NewMockInsulinRepository(ctrl *gomock.Controller) *MockInsulinRepository {
	mock := &MockInsulinRepository{ctrl: ctrl}
	mock.recorder = &MockInsulinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsulinRepository) EXPECT() *MockInsulinRepositoryMockRecorder {
	return m.recorder
}

// GetByTimeRange mocks base method.
func (m *MockInsulinRepository) GetByTimeRange(ctx context.Context, userID int64, from, to time.Time) ([]*domain.InsulinDose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTimeRange", ctx, userID, from, to)
	ret0, _ := ret[0].([]*domain.InsulinDose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTimeRange indicates an expected call of GetByTimeRange.
func (mr *MockInsulinRepositoryMockRecorder) GetByTimeRange(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTimeRange", reflect.TypeOf((*MockInsulinRepository)(nil).GetByTimeRange), ctx, userID, from, to)
}

// GetLast mocks base method.
func (m *MockInsulinRepository) GetLast(ctx context.Context, userID int64, limit int) ([]domain.InsulinDose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.InsulinDose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockInsulinRepositoryMockRecorder) GetLast(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockInsulinRepository)(nil).GetLast), ctx, userID, limit)
}

// Save mocks base method.
func (m *MockInsulinRepository) Save(ctx context.Context, dose *domain.InsulinDose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, dose)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInsulinRepositoryMockRecorder) Save(ctx, dose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInsulinRepository)(nil).Save), ctx, dose)
}
