// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/domain (interfaces: FoodRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_food_repository.go -package=mocks . FoodRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFoodRepository is a mock of FoodRepository interface.
type MockFoodRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFoodRepositoryMockRecorder
	isgomock struct{}
}

// MockFoodRepositoryMockRecorder is the mock recorder for MockFoodRepository.
type MockFoodRepositoryMockRecorder struct {
	mock *MockFoodRepository
}

// NewMockFoodRepository creates a new mock instance.
func NewMockFoodRepository(ctrl *gomock.Controller) *MockFoodRepository {
	mock := &MockFoodRepository{ctrl: ctrl}
	mock.recorder = &MockFoodRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoodRepository) EXPECT() *MockFoodRepositoryMockRecorder {
	return m.recorder
}

// GetByTimeRange mocks base method.
func (m *MockFoodRepository) GetByTimeRange(ctx context.Context, userID int64, from, to time.Time) ([]*domain.FoodEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTimeRange", ctx, userID, from, to)
	ret0, _ := ret[0].([]*domain.FoodEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTimeRange indicates an expected call of GetByTimeRange.
func (mr *MockFoodRepositoryMockRecorder) GetByTimeRange(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTimeRange", reflect.TypeOf((*MockFoodRepository)(nil).GetByTimeRange), ctx, userID, from, to)
}

// GetLast mocks base method.
func (m *MockFoodRepository) GetLast(ctx context.Context, userID int64, limit int) ([]domain.FoodEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.FoodEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockFoodRepositoryMockRecorder) GetLast(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockFoodRepository)(nil).GetLast), ctx, userID, limit)
}

// Save mocks base method.
func (m *MockFoodRepository) Save(ctx context.Context, entry *domain.FoodEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFoodRepositoryMockRecorder) Save(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFoodRepository)(nil).Save), ctx, entry)
}
