// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: CGMUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cgm_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram CGMUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCGMUseCase is a mock of CGMUseCase interface.
type MockCGMUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCGMUseCaseMockRecorder
	isgomock struct{}
}

// MockCGMUseCaseMockRecorder is the mock recorder for MockCGMUseCase.
type MockCGMUseCaseMockRecorder struct {
	mock *MockCGMUseCase
}

// NewMockCGMUseCase creates a new mock instance.
func NewMockCGMUseCase(ctrl *gomock.Controller) *MockCGMUseCase {
	mock := &MockCGMUseCase{ctrl: ctrl}
	mock.recorder = &MockCGMUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCGMUseCase) EXPECT() *MockCGMUseCaseMockRecorder {
	return m.recorder
}

// AddConnection mocks base method.
func (m *MockCGMUseCase) AddConnection(ctx context.Context, userID int64, provider domain.CGMProvider, credential1, credential2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConnection", ctx, userID, provider, credential1, credential2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddConnection indicates an expected call of AddConnection.
func (mr *MockCGMUseCaseMockRecorder) AddConnection(ctx, userID, provider, credential1, credential2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConnection", reflect.TypeOf((*MockCGMUseCase)(nil).AddConnection), ctx, userID, provider, credential1, credential2)
}

// GetConnection mocks base method.
func (m *MockCGMUseCase) GetConnection(ctx context.Context, userID int64) (*domain.CGMConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, userID)
	ret0, _ := ret[0].(*domain.CGMConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockCGMUseCaseMockRecorder) GetConnection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockCGMUseCase)(nil).GetConnection), ctx, userID)
}

// RemoveConnection mocks base method.
func (m *MockCGMUseCase) RemoveConnection(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveConnection", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveConnection indicates an expected call of RemoveConnection.
func (mr *MockCGMUseCaseMockRecorder) RemoveConnection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveConnection", reflect.TypeOf((*MockCGMUseCase)(nil).RemoveConnection), ctx, userID)
}

// TestConnection mocks base method.
func (m *MockCGMUseCase) TestConnection(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockCGMUseCaseMockRecorder) TestConnection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockCGMUseCase)(nil).TestConnection), ctx, userID)
}
