// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: DoseAdvisorUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_advisor_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram DoseAdvisorUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDoseAdvisorUseCase is a mock of DoseAdvisorUseCase interface.
type MockDoseAdvisorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDoseAdvisorUseCaseMockRecorder
	isgomock struct{}
}

// MockDoseAdvisorUseCaseMockRecorder is the mock recorder for MockDoseAdvisorUseCase.
type MockDoseAdvisorUseCaseMockRecorder struct {
	mock *MockDoseAdvisorUseCase
}

// NewMockDoseAdvisorUseCase creates a new mock instance.
func NewMockDoseAdvisorUseCase(ctrl *gomock.Controller) *MockDoseAdvisorUseCase {
	mock := &MockDoseAdvisorUseCase{ctrl: ctrl}
	mock.recorder = &MockDoseAdvisorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoseAdvisorUseCase) EXPECT() *MockDoseAdvisorUseCaseMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockDoseAdvisorUseCase) Analyze(ctx context.Context, userID int64, now time.Time) (*domain.DoseAdvice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, userID, now)
	ret0, _ := ret[0].(*domain.DoseAdvice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockDoseAdvisorUseCaseMockRecorder) Analyze(ctx, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockDoseAdvisorUseCase)(nil).Analyze), ctx, userID, now)
}
