// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: BolusUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_bolus_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram BolusUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBolusUseCase is a mock of BolusUseCase interface.
type MockBolusUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBolusUseCaseMockRecorder
	isgomock struct{}
}

// MockBolusUseCaseMockRecorder is the mock recorder for MockBolusUseCase.
type MockBolusUseCaseMockRecorder struct {
	mock *MockBolusUseCase
}

// NewMockBolusUseCase creates a new mock instance.
func NewMockBolusUseCase(ctrl *gomock.Controller) *MockBolusUseCase {
	mock := &MockBolusUseCase{ctrl: ctrl}
	mock.recorder = &MockBolusUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBolusUseCase) EXPECT() *MockBolusUseCaseMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockBolusUseCase) Calculate(ctx context.Context, userID int64, currentGlucose, carbsGrams float64, now time.Time) (*domain.BolusRecommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, userID, currentGlucose, carbsGrams, now)
	ret0, _ := ret[0].(*domain.BolusRecommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockBolusUseCaseMockRecorder) Calculate(ctx, userID, currentGlucose, carbsGrams, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockBolusUseCase)(nil).Calculate), ctx, userID, currentGlucose, carbsGrams, now)
}
