// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: ActivityUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_activity_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram ActivityUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityUseCase is a mock of ActivityUseCase interface.
type MockActivityUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockActivityUseCaseMockRecorder
	isgomock struct{}
}

// MockActivityUseCaseMockRecorder is the mock recorder for MockActivityUseCase.
type MockActivityUseCaseMockRecorder struct {
	mock *MockActivityUseCase
}

// NewMockActivityUseCase creates a new mock instance.
func NewMockActivityUseCase(ctrl *gomock.Controller) *MockActivityUseCase {
	mock := &MockActivityUseCase{ctrl: ctrl}
	mock.recorder = &MockActivityUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityUseCase) EXPECT() *MockActivityUseCaseMockRecorder {
	return m.recorder
}

// AnalyzeLastActivities mocks base method.
func (m *MockActivityUseCase) AnalyzeLastActivities(ctx context.Context, userID int64, limit int) ([]domain.ActivityAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeLastActivities", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ActivityAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeLastActivities indicates an expected call of AnalyzeLastActivities.
func (mr *MockActivityUseCaseMockRecorder) AnalyzeLastActivities(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeLastActivities", reflect.TypeOf((*MockActivityUseCase)(nil).AnalyzeLastActivities), ctx, userID, limit)
}

// EvaluateImpact mocks base method.
func (m *MockActivityUseCase) EvaluateImpact(activityType domain.ActivityType, durationMin int, intensity domain.Intensity) domain.GlycemicImpact {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateImpact", activityType, durationMin, intensity)
	ret0, _ := ret[0].(domain.GlycemicImpact)
	return ret0
}

// EvaluateImpact indicates an expected call of EvaluateImpact.
func (mr *MockActivityUseCaseMockRecorder) EvaluateImpact(activityType, durationMin, intensity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateImpact", reflect.TypeOf((*MockActivityUseCase)(nil).EvaluateImpact), activityType, durationMin, intensity)
}

// GetLastEntries mocks base method.
func (m *MockActivityUseCase) GetLastEntries(ctx context.Context, userID int64, limit int) ([]domain.ActivityEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEntries", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ActivityEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastEntries indicates an expected call of GetLastEntries.
func (mr *MockActivityUseCaseMockRecorder) GetLastEntries(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEntries", reflect.TypeOf((*MockActivityUseCase)(nil).GetLastEntries), ctx, userID, limit)
}

// SaveEntry mocks base method.
func (m *MockActivityUseCase) SaveEntry(ctx context.Context, userID int64, activityType domain.ActivityType, customType string, durationMin int, intensity domain.Intensity, recordedAt time.Time, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntry", ctx, userID, activityType, customType, durationMin, intensity, recordedAt, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntry indicates an expected call of SaveEntry.
func (mr *MockActivityUseCaseMockRecorder) SaveEntry(ctx, userID, activityType, customType, durationMin, intensity, recordedAt, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntry", reflect.TypeOf((*MockActivityUseCase)(nil).SaveEntry), ctx, userID, activityType, customType, durationMin, intensity, recordedAt, chatID)
}
