// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: GlucoseUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_glucose_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram GlucoseUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGlucoseUseCase is a mock of GlucoseUseCase interface.
type MockGlucoseUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGlucoseUseCaseMockRecorder
	isgomock struct{}
}

// MockGlucoseUseCaseMockRecorder is the mock recorder for MockGlucoseUseCase.
type MockGlucoseUseCaseMockRecorder struct {
	mock *MockGlucoseUseCase
}

// NewMockGlucoseUseCase creates a new mock instance.
func NewMockGlucoseUseCase(ctrl *gomock.Controller) *MockGlucoseUseCase {
	mock := &MockGlucoseUseCase{ctrl: ctrl}
	mock.recorder = &MockGlucoseUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlucoseUseCase) EXPECT() *MockGlucoseUseCaseMockRecorder {
	return m.recorder
}

// GetLastReadings mocks base method.
func (m *MockGlucoseUseCase) GetLastReadings(ctx context.Context, userID int64, limit int) ([]domain.GlucoseReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReadings", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.GlucoseReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReadings indicates an expected call of GetLastReadings.
func (mr *MockGlucoseUseCaseMockRecorder) GetLastReadings(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReadings", reflect.TypeOf((*MockGlucoseUseCase)(nil).GetLastReadings), ctx, userID, limit)
}

// SaveReading mocks base method.
func (m *MockGlucoseUseCase) SaveReading(ctx context.Context, userID int64, value float64, units domain.Units) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReading", ctx, userID, value, units)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveReading indicates an expected call of SaveReading.
func (mr *MockGlucoseUseCaseMockRecorder) SaveReading(ctx, userID, value, units any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReading", reflect.TypeOf((*MockGlucoseUseCase)(nil).SaveReading), ctx, userID, value, units)
}
