// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: NoteUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_note_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram NoteUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteUseCase is a mock of NoteUseCase interface.
type MockNoteUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNoteUseCaseMockRecorder
	isgomock struct{}
}

// MockNoteUseCaseMockRecorder is the mock recorder for MockNoteUseCase.
type MockNoteUseCaseMockRecorder struct {
	mock *MockNoteUseCase
}

// NewMockNoteUseCase creates a new mock instance.
func NewMockNoteUseCase(ctrl *gomock.Controller) *MockNoteUseCase {
	mock := &MockNoteUseCase{ctrl: ctrl}
	mock.recorder = &MockNoteUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteUseCase) EXPECT() *MockNoteUseCaseMockRecorder {
	return m.recorder
}

// SaveNote mocks base method.
func (m *MockNoteUseCase) SaveNote(ctx context.Context, userID int64, noteType domain.NoteType, wellbeing *domain.WellbeingValue, text *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNote", ctx, userID, noteType, wellbeing, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNote indicates an expected call of SaveNote.
func (mr *MockNoteUseCaseMockRecorder) SaveNote(ctx, userID, noteType, wellbeing, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNote", reflect.TypeOf((*MockNoteUseCase)(nil).SaveNote), ctx, userID, noteType, wellbeing, text)
}
