// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: DiaryUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_diary_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram DiaryUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDiaryUseCase is a mock of DiaryUseCase interface.
type MockDiaryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDiaryUseCaseMockRecorder
	isgomock struct{}
}

// MockDiaryUseCaseMockRecorder is the mock recorder for MockDiaryUseCase.
type MockDiaryUseCaseMockRecorder struct {
	mock *MockDiaryUseCase
}

// NewMockDiaryUseCase creates a new mock instance.
func NewMockDiaryUseCase(ctrl *gomock.Controller) *MockDiaryUseCase {
	mock := &MockDiaryUseCase{ctrl: ctrl}
	mock.recorder = &MockDiaryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiaryUseCase) EXPECT() *MockDiaryUseCaseMockRecorder {
	return m.recorder
}

// GetDayEntries mocks base method.
func (m *MockDiaryUseCase) GetDayEntries(ctx context.Context, userID int64, date time.Time, loc *time.Location) ([]*domain.DiaryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDayEntries", ctx, userID, date, loc)
	ret0, _ := ret[0].([]*domain.DiaryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDayEntries indicates an expected call of GetDayEntries.
func (mr *MockDiaryUseCaseMockRecorder) GetDayEntries(ctx, userID, date, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDayEntries", reflect.TypeOf((*MockDiaryUseCase)(nil).GetDayEntries), ctx, userID, date, loc)
}
