// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: FoodUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_food_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram FoodUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFoodUseCase is a mock of FoodUseCase interface.
type MockFoodUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFoodUseCaseMockRecorder
	isgomock struct{}
}

// MockFoodUseCaseMockRecorder is the mock recorder for MockFoodUseCase.
type MockFoodUseCaseMockRecorder struct {
	mock *MockFoodUseCase
}

// NewMockFoodUseCase creates a new mock instance.
func NewMockFoodUseCase(ctrl *gomock.Controller) *MockFoodUseCase {
	mock := &MockFoodUseCase{ctrl: ctrl}
	mock.recorder = &MockFoodUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoodUseCase) EXPECT() *MockFoodUseCaseMockRecorder {
	return m.recorder
}

// GetLastEntries mocks base method.
func (m *MockFoodUseCase) GetLastEntries(ctx context.Context, userID int64, limit int) ([]domain.FoodEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEntries", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.FoodEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastEntries indicates an expected call of GetLastEntries.
func (mr *MockFoodUseCaseMockRecorder) GetLastEntries(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEntries", reflect.TypeOf((*MockFoodUseCase)(nil).GetLastEntries), ctx, userID, limit)
}

// SaveEntry mocks base method.
func (m *MockFoodUseCase) SaveEntry(ctx context.Context, userID int64, carbsGrams float64, note string, eatenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntry", ctx, userID, carbsGrams, note, eatenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntry indicates an expected call of SaveEntry.
func (mr *MockFoodUseCaseMockRecorder) SaveEntry(ctx, userID, carbsGrams, note, eatenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntry", reflect.TypeOf((*MockFoodUseCase)(nil).SaveEntry), ctx, userID, carbsGrams, note, eatenAt)
}
