// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: UserUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram UserUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUseCase is a mock of UserUseCase interface.
type MockUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseMockRecorder
	isgomock struct{}
}

// MockUserUseCaseMockRecorder is the mock recorder for MockUserUseCase.
type MockUserUseCaseMockRecorder struct {
	mock *MockUserUseCase
}

// NewMockUserUseCase creates a new mock instance.
func NewMockUserUseCase(ctrl *gomock.Controller) *MockUserUseCase {
	mock := &MockUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCase) EXPECT() *MockUserUseCaseMockRecorder {
	return m.recorder
}

// GetOrCreateUser mocks base method.
func (m *MockUserUseCase) GetOrCreateUser(ctx context.Context, provider domain.Provider, externalID, displayName string) (*domain.User, *domain.ExternalAccount, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateUser", ctx, provider, externalID, displayName)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.ExternalAccount)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetOrCreateUser indicates an expected call of GetOrCreateUser.
func (mr *MockUserUseCaseMockRecorder) GetOrCreateUser(ctx, provider, externalID, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateUser", reflect.TypeOf((*MockUserUseCase)(nil).GetOrCreateUser), ctx, provider, externalID, displayName)
}

// GetProfile mocks base method.
func (m *MockUserUseCase) GetProfile(ctx context.Context, provider domain.Provider, externalID string) (*domain.User, *domain.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, provider, externalID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.ExternalAccount)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserUseCaseMockRecorder) GetProfile(ctx, provider, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserUseCase)(nil).GetProfile), ctx, provider, externalID)
}

// UpdateCarbsPerUnit mocks base method.
func (m *MockUserUseCase) UpdateCarbsPerUnit(ctx context.Context, userID int64, grams float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarbsPerUnit", ctx, userID, grams)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCarbsPerUnit indicates an expected call of UpdateCarbsPerUnit.
func (mr *MockUserUseCaseMockRecorder) UpdateCarbsPerUnit(ctx, userID, grams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarbsPerUnit", reflect.TypeOf((*MockUserUseCase)(nil).UpdateCarbsPerUnit), ctx, userID, grams)
}

// UpdateUnits mocks base method.
func (m *MockUserUseCase) UpdateUnits(ctx context.Context, userID int64, units domain.Units) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUnits", ctx, userID, units)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUnits indicates an expected call of UpdateUnits.
func (mr *MockUserUseCaseMockRecorder) UpdateUnits(ctx, userID, units any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUnits", reflect.TypeOf((*MockUserUseCase)(nil).UpdateUnits), ctx, userID, units)
}
