// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: InsulinUseCase)
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInsulinUseCase is a mock of InsulinUseCase interface.
type MockInsulinUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInsulinUseCaseMockRecorder
	isgomock struct{}
}

// MockInsulinUseCaseMockRecorder is the mock recorder for MockInsulinUseCase.
type MockInsulinUseCaseMockRecorder struct {
	mock *MockInsulinUseCase
}

// NewMockInsulinUseCase creates a new mock instance.
func NewMockInsulinUseCase(ctrl *gomock.Controller) *MockInsulinUseCase {
	mock := &MockInsulinUseCase{ctrl: ctrl}
	mock.recorder = &MockInsulinUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsulinUseCase) EXPECT() *MockInsulinUseCaseMockRecorder {
	return m.recorder
}

// SaveDose mocks base method.
func (m *MockInsulinUseCase) SaveDose(ctx context.Context, userID int64, dose float64, insulinType domain.InsulinType, drug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDose", ctx, userID, dose, insulinType, drug)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDose indicates an expected call of SaveDose.
func (mr *MockInsulinUseCaseMockRecorder) SaveDose(ctx, userID, dose, insulinType, drug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDose", reflect.TypeOf((*MockInsulinUseCase)(nil).SaveDose), ctx, userID, dose, insulinType, drug)
}

// GetLastDoses mocks base method.
func (m *MockInsulinUseCase) GetLastDoses(ctx context.Context, userID int64, limit int) ([]domain.InsulinDose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastDoses", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.InsulinDose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastDoses indicates an expected call of GetLastDoses.
func (mr *MockInsulinUseCaseMockRecorder) GetLastDoses(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastDoses", reflect.TypeOf((*MockInsulinUseCase)(nil).GetLastDoses), ctx, userID, limit)
}
