// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram (interfaces: UserUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user_usecase.go -package=tgmocks github.com/gmtantsevov/shuggabuddy/internal/delivery/telegram UserUseCase
//

// Package tgmocks is a generated GoMock package.
package tgmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/gmtantsevov/shuggabuddy/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUseCase is a mock of UserUseCase interface.
type MockUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseMockRecorder
	isgomock struct{}
}

// MockUserUseCaseMockRecorder is the mock recorder for MockUserUseCase.
type MockUserUseCaseMockRecorder struct {
	mock *MockUserUseCase
}

// NewMockUserUseCase creates a new mock instance.
func NewMockUserUseCase(ctrl *gomock.Controller) *MockUserUseCase {
	mock := &MockUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCase) EXPECT() *MockUserUseCaseMockRecorder {
	return m.recorder
}

// GetOrCreateUser mocks base method.
func (m *MockUserUseCase) GetOrCreateUser(ctx context.Context, provider domain.Provider, externalID, displayName string) (*domain.User, *domain.ExternalAccount, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateUser", ctx, provider, externalID, displayName)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.ExternalAccount)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetOrCreateUser indicates an expected call of GetOrCreateUser.
func (mr *MockUserUseCaseMockRecorder) GetOrCreateUser(ctx, provider, externalID, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateUser", reflect.TypeOf((*MockUserUseCase)(nil).GetOrCreateUser), ctx, provider, externalID, displayName)
}

// GetProfile mocks base method.
func (m *MockUserUseCase) GetProfile(ctx context.Context, provider domain.Provider, externalID string) (*domain.User, *domain.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, provider, externalID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.ExternalAccount)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserUseCaseMockRecorder) GetProfile(ctx, provider, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserUseCase)(nil).GetProfile), ctx, provider, externalID)
}

// UpdateAdvisorInterval mocks base method.
func (m *MockUserUseCase) UpdateAdvisorInterval(ctx context.Context, userID int64, days int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdvisorInterval", ctx, userID, days)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdvisorInterval indicates an expected call of UpdateAdvisorInterval.
func (mr *MockUserUseCaseMockRecorder) UpdateAdvisorInterval(ctx, userID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdvisorInterval", reflect.TypeOf((*MockUserUseCase)(nil).UpdateAdvisorInterval), ctx, userID, days)
}

// UpdateBasalDose mocks base method.
func (m *MockUserUseCase) UpdateBasalDose(ctx context.Context, userID int64, dose float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasalDose", ctx, userID, dose)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBasalDose indicates an expected call of UpdateBasalDose.
func (mr *MockUserUseCaseMockRecorder) UpdateBasalDose(ctx, userID, dose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasalDose", reflect.TypeOf((*MockUserUseCase)(nil).UpdateBasalDose), ctx, userID, dose)
}

// UpdateBolusDrug mocks base method.
func (m *MockUserUseCase) UpdateBolusDrug(ctx context.Context, userID int64, drug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBolusDrug", ctx, userID, drug)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBolusDrug indicates an expected call of UpdateBolusDrug.
func (mr *MockUserUseCaseMockRecorder) UpdateBolusDrug(ctx, userID, drug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBolusDrug", reflect.TypeOf((*MockUserUseCase)(nil).UpdateBolusDrug), ctx, userID, drug)
}

// UpdateCarbsPerUnit mocks base method.
func (m *MockUserUseCase) UpdateCarbsPerUnit(ctx context.Context, userID int64, grams float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCarbsPerUnit", ctx, userID, grams)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCarbsPerUnit indicates an expected call of UpdateCarbsPerUnit.
func (mr *MockUserUseCaseMockRecorder) UpdateCarbsPerUnit(ctx, userID, grams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCarbsPerUnit", reflect.TypeOf((*MockUserUseCase)(nil).UpdateCarbsPerUnit), ctx, userID, grams)
}

// UpdateSettings mocks base method.
func (m *MockUserUseCase) UpdateSettings(ctx context.Context, userID int64, targetMin, targetMax float64, basalDrug, basalTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, userID, targetMin, targetMax, basalDrug, basalTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserUseCaseMockRecorder) UpdateSettings(ctx, userID, targetMin, targetMax, basalDrug, basalTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserUseCase)(nil).UpdateSettings), ctx, userID, targetMin, targetMax, basalDrug, basalTime)
}

// UpdateTimezone mocks base method.
func (m *MockUserUseCase) UpdateTimezone(ctx context.Context, userID int64, timezone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimezone", ctx, userID, timezone)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimezone indicates an expected call of UpdateTimezone.
func (mr *MockUserUseCaseMockRecorder) UpdateTimezone(ctx, userID, timezone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimezone", reflect.TypeOf((*MockUserUseCase)(nil).UpdateTimezone), ctx, userID, timezone)
}

// UpdateUnits mocks base method.
func (m *MockUserUseCase) UpdateUnits(ctx context.Context, userID int64, units domain.Units) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUnits", ctx, userID, units)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUnits indicates an expected call of UpdateUnits.
func (mr *MockUserUseCaseMockRecorder) UpdateUnits(ctx, userID, units any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUnits", reflect.TypeOf((*MockUserUseCase)(nil).UpdateUnits), ctx, userID, units)
}
